"""add_analytics_events_table

Revision ID: e457f5743fa7
Revises: b3c1d4e2f567
Create Date: 2026-04-06 12:38:36.742402
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e457f5743fa7'
down_revision = 'b3c1d4e2f567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('ux_mode', sa.String(length=20), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event'), 'analytics_events', ['event'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_master_user_profiles_user_id'), 'master_user_profiles', type_='unique')
    op.drop_index(op.f('ix_master_user_profiles_user_id'), table_name='master_user_profiles')
    op.create_index(op.f('ix_master_user_profiles_user_id'), 'master_user_profiles', ['user_id'], unique=True)
    op.drop_constraint(op.f('profiles_user_id_key'), 'profiles', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('profiles_user_id_key'), 'profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_master_user_profiles_user_id'), table_name='master_user_profiles')
    op.create_index(op.f('ix_master_user_profiles_user_id'), 'master_user_profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_master_user_profiles_user_id'), 'master_user_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
